dependencies:
jobs:
    build:
        docker:
            - image: cibuilds/hugo:latest
        working_directory: ~/public_html
        environment:
            HUGO_BUILD_DIR: ~/portfolio
        steps:
            - run: apk update && apk add git
            - checkout
            - run: git submodule sync && git submodule update --init
            - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
            - run: htmlproofer $HUGO_BUILD_DIR --allow-hash-href --check-html --empty-alt-ignore --disable-external
            - add_ssh_keys:
                  fingerprints:
                      - 'xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx'
            - run: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
            - deploy:
                  name: deploy
                  command: |
                      if [ "${CIRCLE_BRANCH}" = "master" ]; then
                        rsync -avce ssh $HUGO_BUILD_DIR $SSH_USER@$SSH_HOST:/var/www/keeganfargher.co.za/D
                      else
                        echo "Not master branch, dry run only"
                      fi
