dependencies:

deployment:
    prod:
        branch: master
        commands:
            - sudo sshpass -p "$SSH_USER" rsync -avz ./public $SSH_HOST:/var/www/keeganfargher.co.za/public_html

test:
    override:
        - 'true'
